### ISSUE TITLE
Аддон "ломает" PlasmoVoice

### ISSUE THREAD

**Issue by stngularity** [plasmoapp/pv-addon-groups#13]
Использую PlasmoVoice версии 2.0.5. При попытке запустить сервер с PlasmoVoice и pv-addon-groups (версии 1.0.3) перестаёт работать не только сам pv-addon-groups, но и PlasmoVoice.

```
[19:09:58 INFO]: [PlasmoVoice] Enabling PlasmoVoice v2.0.5
[19:09:59 INFO]: [PlasmoVoice] LuckPerms permissions listener attached
[19:09:59 ERROR]: Error occurred while enabling PlasmoVoice v2.0.5 (Is it up to date?)
su.plo.voice.libs.kotlin.UninitializedPropertyAccessException: lateinit property voiceServer has not been initialized
        at su.plo.voice.groups.GroupsAddon.getVoiceServer(GroupsAddon.kt:25) ~[pv-addon-groups-1.0.3.jar:?]
        at su.plo.voice.groups.GroupsAddon.onConfigLoaded(GroupsAddon.kt:44) ~[pv-addon-groups-1.0.3.jar:?]
        at su.plo.voice.groups.GroupsAddon.onAddonInitialize(GroupsAddon.kt:35) ~[pv-addon-groups-1.0.3.jar:?]
        at su.plo.voice.addon.VoiceAddonManager.initializeAddon(VoiceAddonManager.kt:133) ~[PlasmoVoice-Paper-2.0.5.jar:?]
        at su.plo.voice.addon.VoiceAddonManager.initializeLoadedAddons(VoiceAddonManager.kt:94) ~[PlasmoVoice-Paper-2.0.5.jar:?]
        at su.plo.voice.server.BaseVoiceServer.loadConfig(BaseVoiceServer.java:255) ~[PlasmoVoice-Paper-2.0.5.jar:?]
        at su.plo.voice.server.BaseVoiceServer.onInitialize(BaseVoiceServer.java:154) ~[PlasmoVoice-Paper-2.0.5.jar:?]
        at su.plo.voice.paper.PaperVoiceServer.onInitialize(PaperVoiceServer.kt:37) ~[PlasmoVoice-Paper-2.0.5.jar:?]
        at su.plo.voice.paper.PaperVoiceLoader.onEnable(PaperVoiceLoader.kt:10) ~[PlasmoVoice-Paper-2.0.5.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-307]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:279) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-307]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
[19:09:59 INFO]: [PlasmoVoice] Disabling PlasmoVoice v2.0.5
[19:09:59 ERROR]: Error occurred while disabling PlasmoVoice v2.0.5 (Is it up to date?)
su.plo.voice.libs.kotlin.UninitializedPropertyAccessException: lateinit property uStats has not been initialized
        at su.plo.voice.paper.PaperVoiceServer.onShutdown(PaperVoiceServer.kt:72) ~[PlasmoVoice-Paper-2.0.5.jar:?]
        at su.plo.voice.paper.PaperVoiceLoader.onDisable(PaperVoiceLoader.kt:14) ~[PlasmoVoice-Paper-2.0.5.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:579) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-307]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:279) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-307]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
[19:09:59 INFO]: [pv-addon-groups] Enabling pv-addon-groups v1.0.3
```

**Comment by stngularity** [comment]
Вместе с этим перестаёт работать и `TabComplete` у плагинов

**Comment by apehum** [comment]
Скинь список плагинов и логи

**Comment by stngularity** [comment]
Плагины:
```
Plugins (17): ArmorStandAdjustor, BetterSleeping4, Brewery, BungeeTabListPlus, ChatEmojis, CoreProtect, GSit, LuckPerms, NoChatReports, PlaceholderAPI, PlasmoVoice, Playtimes*, pv-addon-groups, SkinsRestorer, TimeManager, ViaVersion, WorldEdit
```

Логи: 
```
Starting org.bukkit.craftbukkit.Main
*** Warning, you've not updated in a while! ***
*** Please download a new build as per instructions from https://papermc.io/downloads ***
System Info: Java 17 (OpenJDK 64-Bit Server VM 17.0.7+7) Host: Windows 10 10.0 (amd64)
Loading libraries, please wait...
[19:18:21 INFO]: Building unoptimized datafixer
[19:18:24 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[19:18:29 INFO]: Loaded 7 recipes
[19:18:33 INFO]: Starting minecraft server version 1.19.2
[19:18:33 INFO]: Loading properties
[19:18:33 INFO]: This server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)
[19:18:33 INFO]: Server Ping Player Sample Count: 12
[19:18:33 INFO]: Using 4 threads for Netty based IO
[19:18:33 INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 1 worker threads, and gen parallelism of 1 threads
[19:18:34 INFO]: Default game type: SURVIVAL
[19:18:34 INFO]: Generating keypair
[19:18:34 INFO]: Starting Minecraft server on *:25505
[19:18:34 INFO]: Using default channel type
[19:18:34 INFO]: Paper: Using Java compression from Velocity.
[19:18:34 INFO]: Paper: Using Java cipher from Velocity.
[19:18:36 ERROR]: [STDERR] [org.bukkit.craftbukkit.v1_19_R1.legacy.CraftLegacy] Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[19:18:47 WARN]: Legacy plugin Playtimes v1.4.7 does not specify an api-version.
[19:18:47 INFO]: [Brewery] Loading Brewery v3.1.1
[19:18:47 INFO]: [WorldEdit] Loading WorldEdit v7.2.13+46576cc
[19:18:49 INFO]: Got request to register class com.sk89q.worldedit.bukkit.BukkitServerInterface with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@6e8945b6]
[19:18:49 INFO]: [ArmorStandAdjustor] Loading ArmorStandAdjustor v1.7
[19:18:49 INFO]: [PlaceholderAPI] Loading PlaceholderAPI v2.11.3
[19:18:49 INFO]: [GSit] Loading GSit v1.4.3
[19:18:49 INFO]: [NoChatReports] Loading NoChatReports v1.0.5
[19:18:49 INFO]: [ViaVersion] Loading ViaVersion v4.6.2
[19:18:49 INFO]: [ViaVersion] ViaVersion 4.6.2 is now loaded. Registering protocol transformers and injecting...
[19:18:50 INFO]: [ChatEmojis] Loading ChatEmojis v1.3.2
[19:18:50 INFO]: [BungeeTabListPlus] Loading BungeeTabListPlus v3.6.0
[19:18:50 INFO]: [Playtimes] Loading Playtimes v1.4.7
[19:18:50 INFO]: [CoreProtect] Loading CoreProtect v21.3
[19:18:50 INFO]: [BetterSleeping4] Loading BetterSleeping4 v4.0.2
[19:18:50 INFO]: [LuckPerms] Loading LuckPerms v5.4.58
[19:18:50 INFO]: [ViaVersion] Loading block connection mappings ...
[19:18:51 INFO]: [ViaVersion] Using FastUtil Long2ObjectOpenHashMap for block connections
[19:18:53 INFO]: [SkinsRestorer] Loading SkinsRestorer v14.2.11
[19:18:53 INFO]: [TimeManager] Loading TimeManager v1.7.0
[19:18:53 INFO]: [PlasmoVoice] Loading PlasmoVoice v2.0.5
[19:18:53 INFO]: [pv-addon-groups] Loading pv-addon-groups v1.0.3
[19:18:53 WARN]: [pv-addon-groups] Loaded class com.google.inject.Inject from BetterSleeping4 v4.0.2 which is not a depend or softdepend of this plugin.
[19:18:53 INFO]: Server permissions file permissions.yml is empty, ignoring it
[19:18:53 INFO]: [WorldEdit] Enabling WorldEdit v7.2.13+46576cc
[19:18:53 INFO]: Registering commands with com.sk89q.worldedit.bukkit.BukkitServerInterface
[19:18:53 INFO]: WEPIF: Using the Bukkit Permissions API.
[19:18:54 INFO]: Using com.sk89q.worldedit.bukkit.adapter.impl.v1_19_R1.PaperweightAdapter as the Bukkit adapter
[19:18:56 INFO]: [LuckPerms] Enabling LuckPerms v5.4.58
[19:18:57 INFO]:         __
[19:18:57 INFO]:   |    |__)   LuckPerms v5.4.58
[19:18:57 INFO]:   |___ |      Running on Bukkit - Paper
[19:18:57 INFO]:
[19:18:57 INFO]: [LuckPerms] Loading configuration...
[19:18:58 INFO]: [LuckPerms] Loading storage provider... [MONGODB]
[19:18:59 INFO]: [org.mongodb.driver.cluster] Cluster created with settings {hosts=[127.0.0.1:58175], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms'}
[19:18:59 INFO]: [org.mongodb.driver.connection] Opened connection [connectionId{localValue:2, serverValue:2}] to 127.0.0.1:58175
[19:18:59 INFO]: [org.mongodb.driver.connection] Opened connection [connectionId{localValue:1, serverValue:1}] to 127.0.0.1:58175
[19:18:59 INFO]: [org.mongodb.driver.cluster] Monitor thread successfully connected to server with description ServerDescription{address=127.0.0.1:58175, type=STANDALONE, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=17, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=151031400}
[19:19:00 INFO]: [LuckPerms] Loading internal permission managers...
[19:19:00 INFO]: [LuckPerms] Performing initial data load...
[19:19:01 INFO]: [org.mongodb.driver.connection] Opened connection [connectionId{localValue:3, serverValue:3}] to 127.0.0.1:58175
[19:19:01 INFO]: [LuckPerms] Successfully enabled. (took 5358ms)
[19:19:01 INFO]: [PlasmoVoice] Enabling PlasmoVoice v2.0.5
[19:19:02 INFO]: [PlasmoVoice] LuckPerms permissions listener attached
[19:19:02 ERROR]: Error occurred while enabling PlasmoVoice v2.0.5 (Is it up to date?)
su.plo.voice.libs.kotlin.UninitializedPropertyAccessException: lateinit property voiceServer has not been initialized
        at su.plo.voice.groups.GroupsAddon.getVoiceServer(GroupsAddon.kt:25) ~[pv-addon-groups-1.0.3.jar:?]
        at su.plo.voice.groups.GroupsAddon.onConfigLoaded(GroupsAddon.kt:44) ~[pv-addon-groups-1.0.3.jar:?]
        at su.plo.voice.groups.GroupsAddon.onAddonInitialize(GroupsAddon.kt:35) ~[pv-addon-groups-1.0.3.jar:?]
        at su.plo.voice.addon.VoiceAddonManager.initializeAddon(VoiceAddonManager.kt:133) ~[PlasmoVoice-Paper-2.0.5.jar:?]
        at su.plo.voice.addon.VoiceAddonManager.initializeLoadedAddons(VoiceAddonManager.kt:94) ~[PlasmoVoice-Paper-2.0.5.jar:?]
        at su.plo.voice.server.BaseVoiceServer.loadConfig(BaseVoiceServer.java:255) ~[PlasmoVoice-Paper-2.0.5.jar:?]
        at su.plo.voice.server.BaseVoiceServer.onInitialize(BaseVoiceServer.java:154) ~[PlasmoVoice-Paper-2.0.5.jar:?]
        at su.plo.voice.paper.PaperVoiceServer.onInitialize(PaperVoiceServer.kt:37) ~[PlasmoVoice-Paper-2.0.5.jar:?]
        at su.plo.voice.paper.PaperVoiceLoader.onEnable(PaperVoiceLoader.kt:10) ~[PlasmoVoice-Paper-2.0.5.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-307]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:279) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-307]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
[19:19:02 INFO]: [PlasmoVoice] Disabling PlasmoVoice v2.0.5
[19:19:02 ERROR]: Error occurred while disabling PlasmoVoice v2.0.5 (Is it up to date?)
su.plo.voice.libs.kotlin.UninitializedPropertyAccessException: lateinit property uStats has not been initialized
        at su.plo.voice.paper.PaperVoiceServer.onShutdown(PaperVoiceServer.kt:72) ~[PlasmoVoice-Paper-2.0.5.jar:?]
        at su.plo.voice.paper.PaperVoiceLoader.onDisable(PaperVoiceLoader.kt:14) ~[PlasmoVoice-Paper-2.0.5.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:579) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-307]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:279) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-307]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
[19:19:02 INFO]: [pv-addon-groups] Enabling pv-addon-groups v1.0.3
[19:19:02 WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[19:19:02 WARN]: The server will make no attempt to authenticate usernames. Beware.
[19:19:02 WARN]: Whilst this makes it possible to use BungeeCord, unless access to your server is properly restricted, it also opens up the ability for hackers to connect with any username they choose.
[19:19:02 WARN]: Please see http://www.spigotmc.org/wiki/firewall-guide/ for further information.
[19:19:02 WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[19:19:02 INFO]: Preparing level "world"
[19:19:07 INFO]: Preparing start region for dimension minecraft:overworld
[19:19:07 INFO]: Time elapsed: 255 ms
[19:19:07 INFO]: Preparing start region for dimension minecraft:the_nether
[19:19:07 INFO]: Time elapsed: 70 ms
[19:19:07 INFO]: Preparing start region for dimension minecraft:the_end
[19:19:07 INFO]: Time elapsed: 36 ms
[19:19:07 INFO]: [Brewery] Enabling Brewery v3.1.1
[19:19:07 INFO]: [Brewery] Brewery enabled!
[19:19:07 INFO]: [ArmorStandAdjustor] Enabling ArmorStandAdjustor v1.7
[19:19:08 INFO]: [PlaceholderAPI] Enabling PlaceholderAPI v2.11.3
[19:19:08 INFO]: [PlaceholderAPI] Fetching available expansion information...
[19:19:08 INFO]: [GSit] Enabling GSit v1.4.3
[19:19:09 INFO]: 遠 GSit › Плагин был включен
[19:19:09 INFO]: 遠 GSit › Соединение с PlaceholderAPI успешно!
[19:19:09 INFO]: [PlaceholderAPI] Successfully registered expansion: gsit [1.4.3]
[19:19:09 INFO]: 遠 GSit › Доступна новая версия: 1.4.5!
遠 GSit › Ваша версия: 1.4.3
遠 GSit › Скачайте последнюю версию:
遠 GSit › https://www.spigotmc.org/resources/62325
[19:19:09 INFO]: [NoChatReports] Enabling NoChatReports v1.0.5
[19:19:09 INFO]: [NoChatReports] Loading plugin hooks...
[19:19:09 INFO]: [NoChatReports] Loaded 0 plugin hooks!
[19:19:09 INFO]: [ViaVersion] Enabling ViaVersion v4.6.2
[19:19:09 INFO]: [ViaVersion] ViaVersion detected server version: 1.19.1/2 (760)
[19:19:09 ERROR]: [ViaVersion] ************************************************
[19:19:09 ERROR]: [ViaVersion] You are using unsupported software and may encounter unforeseeable issues.
[19:19:09 ERROR]: [ViaVersion]
[19:19:09 ERROR]: [ViaVersion] We strongly advise against using software to mess with message signing:
[19:19:09 ERROR]: [ViaVersion] Instead of doing the obvious (or nothing at all), these kinds of plugins completely break chat message handling, usually then also breaking other plugins.
[19:19:09 ERROR]: [ViaVersion]
[19:19:09 ERROR]: [ViaVersion] We will not provide support in case you encounter issues possibly related to this software.
[19:19:09 ERROR]: [ViaVersion] ************************************************
[19:19:09 INFO]: [ChatEmojis] Enabling ChatEmojis v1.3.2
[19:19:09 ERROR]: [ChatEmojis] Plugin ChatEmojis v1.3.2 has failed to register events for class xyz.oribuin.chatemojis.hook.VaultHook because net/milkbowl/vault/permission/Permission does not exist.
[19:19:09 INFO]: [PlaceholderAPI] Successfully registered expansion: chatemojis [1.3.2]
[19:19:09 INFO]: [BungeeTabListPlus] Enabling BungeeTabListPlus v3.6.0
[19:19:10 INFO]: [Playtimes] Enabling Playtimes v1.4.7*
[19:19:10 INFO]: [PlayTimes] Plugin is up to date! - 1.4.7
[19:19:10 INFO]: [PlaceholderAPI] Successfully registered expansion: PlayTimes [1.4.6]
[19:19:10 INFO]: [PlayTimes] PlaceholdersAPI Hooked!
[19:19:10 INFO]: [PlayTimes] Successfully loaded.
[19:19:10 INFO]: [CoreProtect] Enabling CoreProtect v21.3
[19:19:10 INFO]: [CoreProtect] CoreProtect был успешно запущен!
[19:19:10 INFO]: [CoreProtect] Для хранения данных используется SQLite.
[19:19:10 INFO]: --------------------
[19:19:10 INFO]: [CoreProtect] Нравится CoreProtect? Присоединяйтесь к нашему Discord!
[19:19:10 INFO]: [CoreProtect] Discord: www.coreprotect.net/discord/
[19:19:10 INFO]: --------------------
[19:19:10 INFO]: [BetterSleeping4] Enabling BetterSleeping4 v4.0.2
[19:19:12 WARN]: [BetterSleeping4] §cYour GSit version is incompatible with this version of BetterSleeping, GSit support cannot enable
[19:19:12 INFO]: [PlaceholderAPI] Successfully registered expansion: bettersleeping [4.0.2]
[19:19:12 INFO]: [SkinsRestorer] Enabling SkinsRestorer v14.2.11
[19:19:13 INFO]: [SkinsRestorer] Detected Minecraft v1_19_R1, using MappingSpigotSkinRefresher.
[19:19:13 INFO]: [SkinsRestorer] -------------------------/Warning\-------------------------
[19:19:13 INFO]: [SkinsRestorer] This plugin is running in PROXY mode!
[19:19:13 INFO]: [SkinsRestorer] You have to do all configuration at config file
[19:19:13 INFO]: [SkinsRestorer] inside your BungeeCord/Velocity server.
[19:19:13 INFO]: [SkinsRestorer] (<proxy>/plugins/SkinsRestorer/)
[19:19:13 INFO]: [SkinsRestorer] -------------------------\Warning/-------------------------
[19:19:13 INFO]: [TimeManager] Enabling TimeManager v1.7.0
[19:19:13 INFO]: [TimeManager] The configuration file already exists.
[19:19:14 INFO]: [TimeManager] The worlds list was actualized.
[19:19:14 INFO]: [TimeManager] Enabled config.yml v1.7.0.
[19:19:14 INFO]: [TimeManager] The language file already exists.
[19:19:14 INFO]: [TimeManager] Default translation is actually set to default.
[19:19:14 INFO]: [TimeManager] default exists in lang.yml, keep it as default translation.
[19:19:14 INFO]: [TimeManager] Multilanguage support is disable.
[19:19:14 INFO]: [TimeManager] Enabled lang.yml v1.7.0.
[19:19:14 INFO]: [TimeManager] The language file already exists.
[19:19:14 INFO]: [TimeManager] The commands scheduler is disable.
[19:19:14 INFO]: [TimeManager] Enabled cmds.yml v1.7.0.
[19:19:15 INFO]: [TimeManager] The plugin is now enabled, timers will be initialized when all the other plugins are loaded.
[19:19:15 INFO]: [PlaceholderAPI] Placeholder expansion registration initializing...
[19:19:15 INFO]: Running delayed init tasks
[19:19:15 INFO]: [CoreProtect] WorldEdit регистрация успешно инициализирована.
[19:19:15 INFO]: Done (42.303s)! For help, type "help"
[19:19:15 INFO]: Timings Reset
[19:19:15 INFO]: [TimeManager] The server's initial tick was set in the config.yml.
[19:19:15 INFO]: [TimeManager] The server's initial tick is #1175110 (16:19:15 UTC).
[19:19:15 INFO]: [TimeManager] The server's current tick is #1175110 (16:19:15 UTC).
[19:19:15 INFO]: [TimeManager] The world world had its time resynchronized to the server time.
[19:19:15 INFO]: [TimeManager] The world world is running since 70 whole day(s) (0001-03-12).
[19:19:15 INFO]: [TimeManager] The world world starts at 06:00:00 (+0 ticks).
[19:19:15 INFO]: [TimeManager] The world world's current time is 06:00:00 (#0).
[19:19:15 INFO]: [TimeManager] The world world's current speed is 1.0.
[19:19:15 INFO]: [TimeManager] The world world_nether had its time resynchronized to the server time.
[19:19:15 INFO]: [TimeManager] The world world_nether is running since 113 whole day(s) (0001-04-24).
[19:19:15 INFO]: [TimeManager] The world world_nether starts at 06:00:00 (+0 ticks).
[19:19:15 INFO]: [TimeManager] The world world_nether's current time is 06:00:00 (#0).
[19:19:15 INFO]: [TimeManager] The world world_nether's current speed is 1.0.
[19:19:15 INFO]: [TimeManager] The world world_the_end had its time resynchronized to the server time.
[19:19:15 INFO]: [TimeManager] The world world_the_end is running since 113 whole day(s) (0001-04-24).
[19:19:15 INFO]: [TimeManager] The world world_the_end starts at 06:00:00 (+0 ticks).
[19:19:15 INFO]: [TimeManager] The world world_the_end's current time is 06:00:00 (#0).
[19:19:15 INFO]: [TimeManager] The world world_the_end's current speed is 1.0.
[19:19:15 INFO]: [TimeManager] All worlds have been syncronized to the server time. If you want to keep them synchronized, set their 'sync' option to true.
[19:19:15 INFO]: [Brewery] Background data loading complete.
[19:19:15 INFO]: [NoChatReports] Checking for updates...
[19:19:15 INFO]: [ViaVersion] Finished mapping loading, shutting down loader executor!
[19:19:15 INFO]: [PlaceholderAPI] Successfully registered expansion: player [2.0.4]
[19:19:15 INFO]: 1 placeholder hook(s) registered!
[19:19:16 INFO]: [SkinsRestorer] ----------------------------------------------
[19:19:16 INFO]: [SkinsRestorer]     +==================+
[19:19:16 INFO]: [SkinsRestorer]     |   SkinsRestorer  |
[19:19:16 INFO]: [SkinsRestorer]     |------------------|
[19:19:16 INFO]: [SkinsRestorer]     |    Proxy Mode    |
[19:19:16 INFO]: [SkinsRestorer]     +==================+
[19:19:16 INFO]: [SkinsRestorer] ----------------------------------------------
[19:19:16 INFO]: [SkinsRestorer]     Current version: 14.2.11
[19:19:16 INFO]: [SkinsRestorer]     This is the latest version!
[19:19:16 INFO]: [SkinsRestorer] ----------------------------------------------
[19:19:16 WARN]: [ViaVersion] There is a newer plugin version available: 4.7.0, you're on: 4.6.2
[19:19:16 INFO]: [NoChatReports] You are running the latest version.
```

**Comment by apehum** [comment]
Скорее всего это из-за конфликта с плагином `BetterSleeping4`. Конфликт будет пофикшен, но не в ближайшее время, там нужно будет большинство аддонов переделывать

**Comment by stngularity** [comment]
Хорошо. Спасибо за информацию (из-за чего происходит эта ошибка) и удачи!
